### PR TITLE
Pull Request 5

### PR DESCRIPTION
**Pull request by michaelmunje**
### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @RobertBedrosian

**Comment by kyledewey** [comment]
Additionally assigned @Sai-Pappu

**Review by RobertBedrosian — COMMENTED** [review]
It took me a bit to understand what you're doing, so its definitely readable but some comments would be nice to speed things up.

**Review by RobertBedrosian — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM but took some googling to figure out some of the Machine learning concepts.

**Pull request merged**
