### PR TITLE
Pull Request 2

### PR DESCRIPTION
**Pull request by michaelmunje**
### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @alejandrom2

**Review by alejandrom2 — CHANGES_REQUESTED** [review]
Although this works. I would probably want to change these to MD files, or TXT. you also want to avoid spaces in file names for source code.

**Comment by michaelmunje** [comment]
Thank you for the feedback @alejandrom2 ! That makes sense, I have added a commit that follows from the suggested changes.

**Review by alejandrom2 — APPROVED** [review]
👍

**Pull request merged**
